projeto7:
  outputs:
    dev:
      dataset: dsadwp7
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /dsa/chave/capitulo15dsa-f8e1375ec20f.json
      location: US
      method: service-account
      priority: interactive
      project: capitulo15dsa
      threads: 1
      type: bigquery
  target: dev